### ISSUE TITLE
Subir artículo Ratibroombroom

### ISSUE THREAD

**Issue by punkto** [aindustriosa/aindustriosa-web#40]

**Comment by crespum** [comment]
@punkto debía haber algo mal en #41 que non sae na páxina principal a miniatura do post...

**Comment by crespum** [comment]
Migramos (migrou @sergiocarracedo) de Travis CI a Github Actions porque o servicio de https://travis-ci.org/ pecha o 31 de maio (hoxe). Agora mesmo xa está despregado.
