### ISSUE TITLE
Xerar e engadir favicon

### ISSUE THREAD

**Issue by crespum** [aindustriosa/aindustriosa-web#5]

**Comment by CyberMODE** [comment]
Mira a ver si vale este
[favicon-2.ico.zip](https://github.com/aindustriosa/aindustriosa-web/files/4433455/favicon-2.ico.zip)

**Comment by crespum** [comment]
Gracias @CyberMODE. Está activo.

**Comment by crespum** [comment]
Volvo a reabrir o issue con un tema que está lixeiramente relacionado. Hai que xerar máis iconos para as previsualizacións do enlace:
![image](https://user-images.githubusercontent.com/1484796/79103909-c21fe980-7d6d-11ea-9613-ae4feee4739e.png)

E ademais hai que quitar o meu nome das mesmas:
![image](https://user-images.githubusercontent.com/1484796/79104052-0c08cf80-7d6e-11ea-8e21-ae9fb5aa12df.png)

Todo isto son meta atributos da web.

**Comment by CyberMODE** [comment]
Podría ser la misma imagen que usáis en la redes sociales? y si fuese una noticia compartida, que sea la primera imagen de la noticia, por ejemplo

**Comment by CyberMODE** [comment]
Tu nombre, lo esta sacando del Autor de la web, no se por que pilla ese meta, si es necesario quitarlo o se puede sustituir por otro:

https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started
